# Generated by Django 2.1.8 on 2021-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(default='')),
                ('category', models.CharField(choices=[('music', 'zene'), ('book', 'könyv'), ('comic', 'képregény'), ('movie', 'film'), ('game', 'videojáték'), ('research', 'kutatás')], default='paint', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
