# Generated by Django 2.1.8 on 2021-04-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='shortcontent',
            field=models.TextField(default='', max_length=200),
        ),
    ]
