# Generated by Django 2.1.8 on 2021-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogpost_shortcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(default='', upload_to='hero_images/'),
        ),
    ]
