# Generated by Django 2.1.8 on 2021-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='embed_code',
            field=models.TextField(default='alma'),
        ),
    ]
