# Generated by Django 2.1.8 on 2021-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_uploader', '0002_imageupload_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='embed_code',
            field=models.TextField(default='<img src="<django.db.models.fields.files.ImageField>">'),
        ),
    ]
