# Generated by Django 2.1.8 on 2021-04-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_uploader', '0003_auto_20210407_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='embed_code',
        ),
    ]
